title: LinuQ : Projets de 2018-2019
author: GitHub User
email: jeanleblond@posteo.net
description: > # this means to ignore newlines until "baseurl:"
  Restez au courant de mes derniers articles publiés en consultant mon blog régulièrement!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
